build/lib/template/helpers/importInterfaces.js
src/lib/template/helpers/importInterfaces.ts

If you have multiple model definitions in paths, they are duplicated in the domains and mock domains:
```yml
/users:
get:
summary: List all users
operationId: usersGet
responses:
'200':
description: Ok
schema:
$ref: '#/definitions/UserModels'
'404':
description: Not found
'/users/{userId}':
get:
summary: Get user
operationId: usersUserIdGet
responses:
'200':
description: Ok
schema:
$ref: '#/definitions/UserModel'
'404':
description: Not found
```
outputs something like this:
```typescript
import {
User,
User,
UserModel,
...
} from '@/http/nodegen/interfaces';
```

Remove duplicated imports in domain and mock stubs

---

build/lib/template/helpers/__tests__/getSingleSuccessResponse.js
build/lib/template/helpers/getSingleSuccessResponse.js
src/lib/template/helpers/__tests__/getSingleSuccessResponse.ts
src/lib/template/helpers/getSingleSuccessResponse.ts

**Is your feature request related to a problem? Please describe.**
By default, the http routes will always generate 200's for success. This means the swagger definitions will disagree with the implementation
**Describe the solution you'd like**
If there is a single success (200-level) response defined in the yml for a route, then it would be cool it the generated files automatically extracted that
**Describe alternatives you've considered**
Manually changing the routes, which results in being overridden on re-generate
**Additional context**
will add `.status(<code>)` if there is only 1 200-level status code in path responses
used by https://github.com/acrontum/openapi-nodegen-typescript-server/pull/8

[FEATURE] infer success status code

---

src/lib/helpers/SwaggerUtils.ts

fix conflicting validations when a string is optional, but also has a minimum length

do not allow empty string if min length required

---

build/cli.js
build/commander.js
build/lib/FileIterator.js
build/lib/helpers/__tests__/endpointNameCalculation.js
build/lib/helpers/endpointNameCalculation.js
build/lib/openapi/OpenAPIBundler.js
package.json
src/cli.ts
src/commander.ts
src/interfaces/Config.ts
src/interfaces/GenerateOperationFileConfig.ts
src/interfaces/NodegenRc.ts
src/lib/FileIterator.ts
src/lib/helpers/__tests__/endpointNameCalculation.ts
src/lib/helpers/endpointNameCalculation.ts
src/lib/openapi/OpenAPIBundler.ts

turn this: 
/item/{id}/comment/thing
into this:
itemIdThing
low hanging fruit - adds a little more flexibility
src/lib/helpers/__tests__/endpointNameCalculation.ts shows more use cases.

feat: segmentSecondGrouping for versioned apis and grouping monolitic beastly api's

---

src/cli.ts

if `--yes` flag is passed in, version check won't block but will still report newer versions

report version mismatch, but proceed anyway

---

src/lib/helpers/extractOASchemaPathResponses.ts
src/lib/openapi/OpenAPIInjectInterfaceNaming.ts

Extract the first 200-level response (as opposed to only 200), and use that for validation.
Use case: POST that returns the newly created entity, or a `runningJobId` (for example).

FEAT: transform all 200-level responses

---

src/commander.ts
src/lib/template/TemplateFetch.ts
src/lib/template/__tests__/TemplateFetch.ts

Re-petitioning for this feature.
Opened a while back, but wasn't really necessary. Still isn't, but makes local dev much simpler.
To address the concern about encouraging unshared code - people can do that by setting up private template repos anyway, so we're not really solving that issue anyway, but maybe we could just leave this sneak feature out of the docs so that at least people will not jump to local templates by default.
open for discussion - I've been using this locally for a while, but would save me a rebase and rebuild each time in the future, so I'm a bit biased here for sure

Allow local template folder

---

.gitignore
package-lock.json
package.json
src/lib/FileIterator.ts
src/lib/helpers/__tests__/isFileToIngore.ts
src/lib/helpers/isFileToIngore.ts
src/types.d.ts

started by adding ignored folders to the walker, but it stopped working properly. 
looked into the readme for instructions and basically pointed to this way better walk, so replaced it, fixed and wired up the ignore checker.
- added test junk to gitignore
- new walker doesn't have types, so just yolo in an any module
- cleaned up and added some more folder pattern checks
- result is significantly faster, which is nice for tests too

replace walk with faster walk; fix file ignore to properly skip targets

---

src/lib/helpers/isFileToIngore.ts

might make sense to add some configuration options here, but just added common build outputs to the default ignore files

add build folders to default ignore

---

package-lock.json
package.json
src/lib/helpers/NamingUtils.ts

Since the operation is almost always already camelCase, this should only affect the edge case (something like `x2y`)

Update namer method to always camelcase

---

src/lib/template/helpers/mockOutput.ts

if schema specifies `x-passRequest` then the mocks would hang without calling `res.end`.

Fix hanging tests which use mockers

---

src/lib/helpers/SwaggerUtils.ts

nullable is supported in oa3, oa2 solution recommends x-nullable
https://swagger.io/docs/specification/data-models/data-types/#null
https://jane.readthedocs.io/en/latest/tips/nullable.html
the problem:
body params are assumed to be nullable, which means a patch can unset a field even if it has min-length validation
solution:
```yaml
type: object
properties:
name:
type: string
nullable: false # oa3
x-nullable: false # oa2
```
alternatively, making a new model for post/patch/get if the params differ

ENH: disallow null in body params with x-nullable (oa2) or nullable (oa3)

---

package-lock.json
src/lib/helpers/__tests__/getBaseUrl.ts
src/lib/helpers/getBaseUrl.ts
src/lib/openapi/OpenAPIBundler.ts
test_openapi3.yml

Try to parse baseUrl from spec.
Skipped if it already has it in the spec (OA2), or parsed from server.urls array (OA3).
If urls do not have a common base path (full path), ignore and return '/'. Some time down the road could be clever and find the lowest shared base path, but basic support should come first.

support swagger.baseurl in templates when using OA3

---

src/lib/helpers/SwaggerUtils.ts

When i reviewed the other PR on the file diff I had this still in my local repo...
Basically allows you to do array any - I think I held back as this sort of stuff will just encourage sloppy swagger files.. in my case i just wanted to be lazy.. but this stopped me as without this fix the output is Joi.array().items(undefined)
It is more a discussion topic that a PR.. but don't be shy to kick this back, twas easier to explain this way.

do not add the content unless there is content to add

---

src/__tests__/openapiNodegen_oa3.ts
src/lib/openapi/oa3toOa2Body.ts
test_openapi3.yml

Also added a catch all which would just take whatever the first content-type is and use that as body - will definitely not work if an endpoint supports multiple content type responses
closes acr-lfr/generate-it-typescript-server#164 
closes acr-lfr/generate-it-typescript-server#163

Map oa3 multipart content type to formData instead of body

---

package-lock.json
package.json
src/lib/generate/GeneratedComparison.ts

Had this a few times in the output:
```
Nodegen directory structure ready
Something went wrong:
Trace: TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at GeneratedComparison.fileDiffsPrint (/test/node_modules/generate-it/build/lib/generate/GeneratedComparison.js:111:16)
at /test/node_modules/generate-it/build/generateIt.js:48:50
at step (/test/node_modules/tslib/tslib.js:143:27)
at Object.next (/test/node_modules/tslib/tslib.js:124:57)
at fulfilled (/test/node_modules/tslib/tslib.js:114:62)
at /test/node_modules/generate-it/build/cli.js:43:25
at step (/test/node_modules/tslib/tslib.js:143:27)
at Object.next (/test/node_modules/tslib/tslib.js:124:57)
at /test/node_modules/tslib/tslib.js:117:75
at new Promise (<anonymous>)
at Object.__awaiter …
```

fix issue with file diff trying to print undefined / null

---

src/lib/helpers/SwaggerUtils.ts
src/lib/helpers/__tests__/SwaggerUtils.ts

**Generated type (before and after the patch - right):**
```ts
export interface AdminProfilesGetQuery {
dbQueryProfile?: DbQueryProfile;
}
export interface DbQueryProfile {
filter?: // ...
}
```
**Generated validations (before the patch - wrong):**
```ts
export default {
adminProfilesGet: {
query: Joi.object({
// ... key "dbQueryProfile" is missing :(
filter: // ...
})
};
```
**Generated validations (after the patch - right):**
```ts
export default {
adminProfilesGet: {
query: Joi.object({
dbQueryProfile: Joi.object({
// ... key "dbQueryProfile" is here :)
filter: // ...
})
})
};
```

fix: validator function skips query param key when param is of type "object"

---

src/lib/helpers/SwaggerUtils.ts
src/lib/helpers/__tests__/SwaggerUtils.ts

Please ensure your pull request:
- ~Includes additions to the docs, found in the /docs, as required~
- ✓The new and changed code you have written is unit tested and passes the eslint 
- ✓The body of the text for this PR includes enough text for a reviewer to understand the context of the change
validators were not being added when value was zero
```typescript
if (Number(param.minLength)) { // fails the check here, if explicit zero passed
```
changed to check if is numeric - ie. if number cast does not return NaN

fix: min / max validators failed if value was zero

---

src/lib/helpers/__tests__/checkRcOpIdArrIsValid.ts
src/lib/helpers/checkRcOpIdArrIsValid.ts

Please ensure your pull request:
- Includes additions to the docs, found in the /docs, as required
- The new and changed code you have written is unit tested and passes the eslint
- The body of the text for this PR includes enough text for a reviewer to understand the context of the change
Previously the code was wrong - it prevented the sub arr have the same id as on in the pub... what it should have been doing is stopping the user from have dupes in the sub and dupes in the pub.
This fix corrects the check and allows 1 service to pub and sub to the same opId

permit 1 service to publish and subscribe to the same id

---

src/__tests__/openapiNodegen_full.ts
src/lib/template/helpers/pathParamsToDomainParams.ts

closes acr-lfr/generate-it-typescript-server#161 (pending acr-lfr/generate-it-typescript-server#179)
Please ensure your pull request:
- ~Includes additions to the docs, found in the /docs, as required~
- ~The new and changed code you have written is unit tested~ and passes the eslint
- The body of the text for this PR includes enough text for a reviewer to understand the context of the change (see issue)

add express response to res with x-pass-response

---

docs/_pages/features.md
package-lock.json
package.json
src/generateIt.ts
src/interfaces/ConfigExtendedBase.ts
src/interfaces/NodegenRc.ts
src/lib/Injections.ts
src/lib/template/__tests__/TemplateFetch.ts

This injector merges over files from tpl files in an opt'in fashion.
Example:
1. The original tpl repo: https://github.com/acr-lfr/generate-it-typescript-server 
2. The injector example repo: https://github.com/j-d-carmichael/test-injection-repo 
3. An example dummy API ( https://github.com/j-d-carmichael/api-dummy/tree/typeorm ):
- Generated with the generate-it-typescript-server
- .nodegenrc file contains the inection block
- The injection references the aforementioned test-injeciton-repo
What happens when the generate-server on the dummy api:
1. normal ts server tpl is downloaded
2. sees the injection block in the rc file (https://github.com/j-d-carmichael/api-dummy/blob/typeorm/.nodegenrc#L7)
3. creates a new "_merged" folder (a copy of the previously downloaded tpl, minus the .git …

Feature/injections 

---

docs/_pages/templates.md
package-lock.json
package.json
src/__mocks__/mockConfig.ts
src/interfaces/NodegenRc.ts
src/lib/__tests__/OpenAPIInjectInterfaceNaming.ts
src/lib/generate/__tests__/generateTypeScriptInterfaceText.ts
src/lib/generate/generateTypeScriptInterfaceText.ts
src/lib/openapi/OpenAPIBundler.ts
src/lib/openapi/OpenAPIInjectInterfaceNaming.ts

Allow custom QuickType options in .nodegenrc (i.e. `"prefer-unions": true`).
There are no changes to the existing behavior, since this is only an opt-in, not opt-out feature.

feat: Allow custom QuickType options in .nodegenrc

---

package-lock.json
package.json
src/lib/helpers/OaToJsToJs.ts
src/lib/helpers/__tests__/OaToJsToJs.spec.ts

Create an attribute in a key with a - and previously it would break the function paramsOutputReducer.ts
This PR now checks if the key should be wrapped and wraps it in ['  ']

ensure attributes are wrapped when needed

---

docs/_pages/features.md
package-lock.json
package.json
src/__tests__/openapiNodegen_full.ts
src/interfaces/NodegenRc.ts
src/lib/Injections.ts
test_server/.openapi-nodegen/git/httpsGithubComAcrontumOpenapiNodegenTypescriptServerGit/.nodegenrc

As the title says
```
"injections": [
{
"isBaseTpl": true
"source": "https://github.com/acr-lfr/generate-it-typescript-server.git"
}
{
"source": "https://github.com/yourusername/ts-overwrites",
"deleteFiles": [
"src/services/PermissionService.ts"
]
}
]
```
You can place the deleteFiles in any injection object, they will be removed from the merge file before generate-it generates the output. 
This is a missing feature of injections - for example, we brought the permission and access service to common helpers for central control. We override this in our injection tpl
src/http/nodegen/middleware/accessTokenMiddleware.ts:
```
export default (headerNames: string[], options?: ValidateRequestOptions) => {
return (req: NodegenRequest, res: express.Response, next: express.NextFunction) => {
/**
* …
```

feat: injections can delete files

---

package-lock.json
package.json
src/lib/helpers/SwaggerUtils.ts
src/lib/helpers/__tests__/SwaggerUtils.ts

For objects with nested objects that are required... the required fields were not being passed in.
There was simply a line missing, added. Unit test added.
What was happening before was...
```
{
in: 'body',
name: 'teamsPostPost',
required: true,
schema: {
type: 'object',
properties: {
team: {
type: 'object',
required: ['name', 'isPremium'],
properties: {
name: {type: 'string', minLength: 1},
isPremium: {type: 'boolean'},
},
},
invitations: {
type: 'array',
items: {
type: 'object',
required: ['roleId'],
properties: {
id: {type: 'number'},
name: {type: 'string'},
email: {type: 'string'},
roleId: {type: 'number'},
invitationLink: {type: 'string'},
action: {
type: 'string',
enum: ['create', 'update', 'delete'],
},
},
},
},
invitationsLanguage: {type: 'string'},
},
},
},
```
Resulted in a Joi …

fix: required fields on nested object was missing

---

CHANGELOG.md
package-lock.json
package.json
src/lib/helpers/SwaggerUtils.ts
src/lib/helpers/__tests__/SwaggerUtils.ts

Previously this was blindly setting all valid joi params to strings which fails for input of type number or integer

fix: enums and test for type number

---

CHANGELOG.md
package-lock.json
package.json
src/lib/helpers/SwaggerUtils.ts
src/lib/helpers/__tests__/SwaggerUtils.ts

When the body is defined as 
```
{
in: 'body',
name: 'v1UserPasswordAnyPut',
required: true,
schema: {
type: 'object'
},
}
```
output joi any:
```
'body': Joi.any(),
```
currently it breaks and injects the body object name as a param, which is complete wrong.
new test case added and existing tests on the joi output all still pass

feat/fix: output joi any
